/*
 *
 * MaterialFactory.hh header template generated by fclass
 * Creation date : Tue Aug 28 15:00:53 2012
 * Copyright (c) 2012 Rémi Eté
 * All Right Reserved.
 *
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 *
 * Written by : R. Eté
 */


#ifndef MATERIALFACTORY_HH
#define MATERIALFACTORY_HH

#include <iostream>
#include <string>
#include <cstdlib>
#include <cmath>

// Geant4 includes
#include "G4NistManager.hh"
#include "G4Material.hh"
#include "G4Element.hh"
#include "globals.hh"

// log4cplus includes
#include <log4cplus/logger.h>
#include <log4cplus/loggingmacros.h>

class MaterialFactory
{

protected :

	static G4Material *GetG10Material() ;
	static G4Material *GetAr_70_CO2_30Material() ;
	static G4Material *GetAr_45_CO2_15_CF4_40Material() ;

public :
	MaterialFactory() ;
	virtual ~MaterialFactory() ;
	static G4bool NistElementIsAvailable(const G4String &eltName) ;
	static G4Material *GetMaterial(const G4String&) ;


};

#endif  // MATERIALFACTORY_HH
