/// \file MaterialFactory.cc
/*
 *
 * MaterialFactory.cc cpp file template generated by fclass
 * Creation date : Tue Aug 28 15:00:53 2012
 * Copyright (c) 2012 Rémi Eté
 * All Right Reserved.
 *
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 *
 * Written by : R. Eté
 */


#include "MaterialFactory.hh"

using namespace std ;
//using namespace log4cplus ;

MaterialFactory::MaterialFactory() {}

MaterialFactory::~MaterialFactory() {}

// Check if eltName exists in NIST database. If yes, returns true.
G4bool MaterialFactory::NistElementIsAvailable(const G4String &eltName) {

   G4bool isAvailable = false ;
   const vector<G4String> availableElementVector = G4NistManager::Instance()->GetNistElementNames() ;

   for(unsigned int i=0 ; i<availableElementVector.size() ; i++) {
      if (eltName == availableElementVector.at(i)) {
	 isAvailable = true ;
	 break ;
      }
   }
   return isAvailable ;
}

G4Material *MaterialFactory::GetG10Material() {

   G4Material *C  = G4NistManager::Instance()->FindOrBuildMaterial("G4_C") ;
   G4Material *H  = G4NistManager::Instance()->FindOrBuildMaterial("G4_H") ;
   G4Material *O  = G4NistManager::Instance()->FindOrBuildMaterial("G4_O") ;
   G4Material *Si = G4NistManager::Instance()->FindOrBuildMaterial("G4_Si") ;

   G4Material *g10Material = new G4Material("G10", 1.9*g/cm3, 4) ;
   g10Material->AddMaterial(C,0.1323) ;
   g10Material->AddMaterial(H,0.03257) ;
   g10Material->AddMaterial(O,0.48316) ;
   g10Material->AddMaterial(Si,0.35194) ;

   return g10Material ;
}

G4Material *MaterialFactory::GetAr_70_CO2_30Material() {

   G4Material *Ar = G4NistManager::Instance()->FindOrBuildMaterial("G4_Ar") ;
   G4Material *CO2 = G4NistManager::Instance()->FindOrBuildMaterial("G4_CARBON_DIOXIDE") ;
   G4double mixtureDensity = (Ar->GetDensity() * 70/100.0 + CO2->GetDensity() * 30/100.0) ;

   G4Material *gasMaterial = new G4Material("Ar/CO2",mixtureDensity,2) ;
   gasMaterial->AddMaterial(Ar ,0.7) ;
   gasMaterial->AddMaterial(CO2,0.3) ;

   return gasMaterial ;
}

G4Material *MaterialFactory::GetAr_45_CO2_15_CF4_40Material() {

   G4int numel, natoms ;
   G4double density, temperature, pressure, a , z;
   G4String name,symbol;

   // Carbon
   a=12.01*g/mole;
   G4Element* elC = new G4Element(name="Carbon", symbol="C", z=6., a);

   //Fluorine
   a=18.998*g/mole;
   G4Element* elF = new G4Element(name="Fluorine", symbol="F", z=9., a);  


   G4Material *Ar = G4NistManager::Instance()->FindOrBuildMaterial("G4_Ar") ;
   G4Material *CO2 = G4NistManager::Instance()->FindOrBuildMaterial("G4_CARBON_DIOXIDE") ;

   //CF4
   //no data available at room temp and pressure;
   density=0.003884*g/cm3;
   temperature=273.15*kelvin;
   pressure=1.0*atmosphere;
   a=88.01*g/mole;
   G4Material* CF4 = new G4Material(name="CF4", density, numel=2, kStateGas, temperature, pressure);
   CF4->AddElement(elC, natoms=1) ;
   CF4->AddElement(elF, natoms=4) ; 

   G4double mixtureDensity = (Ar->GetDensity() * 45/100.0 + CO2->GetDensity() * 15/100.0 + CF4->GetDensity() * 40/100.0) ;

   G4Material *gasGemMaterial = new G4Material("Ar/CO2/CF4",mixtureDensity,3) ;
   gasGemMaterial->AddMaterial(Ar ,0.45) ;
   gasGemMaterial->AddMaterial(CO2,0.15) ;
   gasGemMaterial->AddMaterial(CF4,0.40) ;


   return gasGemMaterial ;

} 


G4Material *MaterialFactory::GetMaterial(const G4String &matName) {

   //Logger logFile = Logger::getInstance("Logger") ;
   G4Material* material = NULL ;
   if(NistElementIsAvailable(matName)) {
      material = G4NistManager::Instance()->FindOrBuildMaterial(matName) ;
   }
   else if (matName  == "G10") {
      material = GetG10Material() ;
   }
   else if (matName == "Ar_70_CO2_30") {
      material = GetAr_70_CO2_30Material() ;
   }
   else if (matName == "Ar_45_CO2_15_CF4_40") {
      material = GetAr_45_CO2_15_CF4_40Material() ;
   }
   else {
      cerr << "Material with name '"<< matName << "' doesn't exists! Can't return a default element!" << endl ; 
      //LOG4CPLUS_FATAL(logFile,"Material with name '"<< matName << "' doesn't exists! Can't return a default element!" ) ;
      exit(1) ;
   }

   return material ;

}
